version = 0.1
[default.deploy.parameters]
stack_name = "board-games-tracker"
s3_bucket = "board-games-tracker-deployment"
s3_prefix = "board-games-tracker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true
image_repositories = []
region = "eu-north-1"
