AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Board Games Pre-Order Tracker

Resources:
  BoardGamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: board-games-preorders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  BoardGamesTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref BoardGamesTable
          SES_SENDER_EMAIL: !Sub '{{resolve:ssm:/board-games-tracker/SES_SENDER_EMAIL}}'
          RECEIVER_EMAIL: !Sub '{{resolve:ssm:/board-games-tracker/RECEIVER_EMAIL}}'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt BoardGamesTable.Arn
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/board-games-tracker/*'
      Events:
        DailyCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)
            Description: Daily check for pre-order updates at 9:00 AM UTC

Outputs:
  BoardGamesTrackerFunction:
    Description: Board Games Tracker Lambda Function ARN
    Value: !GetAtt BoardGamesTrackerFunction.Arn
  BoardGamesTable:
    Description: Board Games DynamoDB Table Name
    Value: !Ref BoardGamesTable 